Ability to configure energy delta decimals + idle status emission
xoseperez/node-red-contrib-power-monitor pull request #13
Opened 2022-02-13 16:48 UTC by krasnyt

I'd like to add the ability to control decimals on the output energy delta, useful especially for low-energy devices. Then I also added an option to configure if the node should emit "idle" state events (most likely on incoming 0-power inputs).

2022-02-13 18:01 UTC, xoseperez requested changes
Check default value for energydecimals so it does not break existing flows.

2022-02-13 20:23 UTC, krasnyt commented on power-monitor/power-monitor.html
> +            this.energydecimals = this.energydecimals || 0;
Good point, fixed.

2022-02-15 10:09 UTC, merged

2022-02-15 10:39 UTC, krasnyt commented
@xoseperez thx. what has to be done now in order to release a new version? I'm not really familiar with these processes.

2022-02-15 11:11 UTC, xoseperez commented
Already pushed to npm repo, should be available soon