Enhanced Documentation
xoseperez/node-red-contrib-power-monitor pull request #22
Opened 2022-10-29 16:18 UTC by SimonButtazzi

Added some words about configuration and output examples

2022-10-29 17:17 UTC, SimonButtazzi commented
Fixed "stop after" x messages (pre_stop state).
State didn't work for stop after > 1.

2022-10-30 21:57 UTC, xoseperez commented on package.json
> +    "version": "1.2.3",
Set it to 1.2.1

2022-10-30 21:58 UTC, xoseperez requested changes
Since this is a minor change and bug fix, version should ber 1.2.1

2022-10-31 17:51 UTC, SimonButtazzi commented
> Since this is a minor change and bug fix, version should be 1.2.1
You are right, initially I added docs and fixed the bug in a new version.
-> Changed version

2022-11-07 08:15 UTC, SimonButtazzi commented on package.json
> +    "version": "1.2.3",
Hey, can you please merge?
Fix was committed, see last comment.

Thanks, Simon

2022-11-07 09:56 UTC, xoseperez approved these changes

2022-11-07 09:57 UTC, merged

2022-11-07 10:02 UTC, xoseperez commented
Merged and updated on npmjs.